#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


def write_if_changed(path: Path, content: str) -> None:
    encoded = content.encode("utf-8")
    if path.exists() and path.read_bytes() == encoded:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded)


def copy_if_changed(source: Path, destination: Path) -> None:
    payload = source.read_bytes()
    if destination.exists() and destination.read_bytes() == payload:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(payload)


def csharp_identifier(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    result = "".join(part[:1].upper() + part[1:] for part in parts)
    if not result or result[0].isdigit():
        result = "Operation" + result
    return result


def generate_openapi(root: Path) -> None:
    source = root / "02-protocol/openapi/openapi.yaml"
    spec: dict[str, Any] = yaml.safe_load(source.read_text(encoding="utf-8"))
    operations: list[tuple[str, str, str]] = []
    for route, path_item in spec["paths"].items():
        for method in ("get", "post", "put", "patch", "delete"):
            operation = path_item.get(method)
            if operation:
                operations.append((operation["operationId"], method.upper(), route))
    operations.sort(key=lambda value: value[0])

    lines = [
        "// <auto-generated />",
        "using System.Text.Json;",
        "",
        "namespace RemoteSupport.Contracts.Generated;",
        "",
        "public sealed record ApiContractOperation(string OperationId, string Method, string Route);",
        "public sealed record ApiContractRequest(JsonElement? Body, IReadOnlyDictionary<string, string> Parameters);",
        "public sealed record ApiContractResponse(int StatusCode, JsonElement? Body);",
        "",
        "public static class OpenApiContract",
        "{",
        "    public static IReadOnlyList<ApiContractOperation> Operations { get; } =",
        "    [",
    ]
    lines.extend(f'        new("{operation}", "{method}", "{route}"),' for operation, method, route in operations)
    lines.extend(["    ];", "}", ""])
    for interface_name in ("IRemoteSupportApiClient", "IRemoteSupportApiHandler"):
        lines.extend([f"public interface {interface_name}", "{"])
        for operation, _, _ in operations:
            lines.append(f"    ValueTask<ApiContractResponse> {csharp_identifier(operation)}Async(ApiContractRequest request, CancellationToken cancellationToken);")
        lines.extend(["}", ""])
    write_if_changed(root / "src/shared-contracts/RemoteSupport.Contracts/Generated/OpenApiContract.g.cs", "\n".join(lines))


def generate_error_codes(root: Path) -> None:
    catalog = (root / "09-templates/error-codes.md").read_text(encoding="utf-8")
    codes = sorted(set(re.findall(r"^\| `([A-Z0-9_]+)` \|", catalog, re.MULTILINE)))
    lines = [
        "// <auto-generated />",
        "namespace RemoteSupport.Contracts.Generated;",
        "",
        "public static class ErrorCodes",
        "{",
    ]
    for code in codes:
        lines.append(f'    public const string {csharp_identifier(code)} = "{code}";')
    lines.extend(["", "    public static IReadOnlyList<string> All { get; } =", "    ["])
    lines.extend(f"        {csharp_identifier(code)}," for code in codes)
    lines.extend(["    ];", "}", ""])
    write_if_changed(root / "src/shared-contracts/RemoteSupport.Contracts/Generated/ErrorCodes.g.cs", "\n".join(lines))


def copy_contracts(root: Path) -> None:
    copy_if_changed(root / "02-protocol/openapi/openapi.yaml", root / "schemas/openapi/openapi.yaml")
    for source in [root / "02-protocol/protobuf/remote_support.proto", root / "02-protocol/ipc/service_ipc.proto"]:
        copy_if_changed(source, root / "schemas/protobuf" / source.name)
    for source in sorted((root / "02-protocol/schemas").glob("*.json")):
        destination = "events" if source.name == "audit-event.schema.json" else "config"
        copy_if_changed(source, root / "schemas" / destination / source.name)
    copy_if_changed(root / "02-protocol/native/remote_support_native.h", root / "src/shared-contracts/native/remote_support_native.h")


def generate_cpp_protobuf(root: Path) -> None:
    protoc = root / ".tools/nuget/grpc.tools/2.81.1/tools/windows_x64/protoc.exe"
    if not protoc.exists():
        raise RuntimeError("Grpc.Tools is not restored; run build.ps1 -Target Restore first.")
    output = root / "src/shared-contracts/generated/cpp"
    output.mkdir(parents=True, exist_ok=True)
    subprocess.run([
        str(protoc),
        f"--proto_path={root / 'schemas/protobuf'}",
        f"--cpp_out={output}",
        "remote_support.proto",
        "service_ipc.proto",
    ], cwd=root / "schemas/protobuf", check=True)


def write_manifest(root: Path) -> None:
    roots = [
        root / "schemas",
        root / "src/shared-contracts/generated",
        root / "src/shared-contracts/RemoteSupport.Contracts/Generated",
        root / "src/shared-contracts/native",
    ]
    files = sorted(
        (path for directory in roots for path in directory.rglob("*") if path.is_file()),
        key=lambda path: path.relative_to(root).as_posix(),
    )
    entries = []
    for path in files:
        payload = path.read_bytes()
        entries.append({
            "path": path.relative_to(root).as_posix(),
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
        })
    write_if_changed(
        root / "artifacts/contracts/generated-contracts.json",
        json.dumps({"schemaVersion": 1, "files": entries}, indent=2) + "\n",
    )


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate_contracts.py REPOSITORY_ROOT")
    root = Path(sys.argv[1]).resolve()
    copy_contracts(root)
    generate_openapi(root)
    generate_error_codes(root)
    generate_cpp_protobuf(root)
    write_manifest(root)
    print("Generated OpenAPI, Protobuf, JSON Schema, and native ABI contract artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

