-- Remote Support Platform PostgreSQL schema baseline v1.3.
-- IDs are generated by the application as UUIDv7 unless a later ADR changes this.
-- Timestamps are UTC timestamptz and are supplied by the application/database transaction.
-- Apply through versioned migrations; do not run this file directly against production.

create table identity_providers (
    id uuid primary key,
    issuer text not null,
    display_name text not null,
    status text not null check (status in ('ACTIVE','DISABLED')),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (issuer)
);

create table users (
    id uuid primary key,
    identity_provider_id uuid not null references identity_providers(id),
    external_subject text not null,
    display_name text not null,
    email_normalized text,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    disabled_at timestamptz,
    unique (identity_provider_id, external_subject)
);

create table tenants (
    id uuid primary key,
    name text not null,
    slug text not null,
    status text not null check (status in ('ACTIVE','SUSPENDED','CLOSED')),
    plan_code text not null,
    data_region text not null,
    retention_days integer not null check (retention_days between 1 and 3650),
    authorization_version bigint not null default 1 check (authorization_version >= 1),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    closed_at timestamptz,
    unique (slug)
);

create table tenant_settings (
    tenant_id uuid primary key references tenants(id) on delete cascade,
    settings_version bigint not null check (settings_version >= 1),
    settings jsonb not null,
    updated_by_user_id uuid references users(id),
    updated_at timestamptz not null
);

create table memberships (
    tenant_id uuid not null references tenants(id) on delete cascade,
    user_id uuid not null references users(id),
    roles text[] not null,
    group_claims text[] not null default '{}',
    status text not null check (status in ('ACTIVE','SUSPENDED','REMOVED')),
    privilege_version bigint not null default 1 check (privilege_version >= 1),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    removed_at timestamptz,
    primary key (tenant_id, user_id),
    check (cardinality(roles) > 0),
    check (roles <@ array['OWNER','ADMIN','SECURITY_AUDITOR','OPERATOR','READ_ONLY_ANALYST']::text[])
);
create index ix_memberships_user_active on memberships(user_id, tenant_id)
  where status = 'ACTIVE';

create table device_groups (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    name text not null,
    description text,
    version bigint not null default 1 check (version >= 1),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (tenant_id, name),
    unique (id, tenant_id)
);

create table devices (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    installation_id uuid not null,
    display_name text not null,
    architecture text not null check (architecture in ('x64','arm64')),
    os_version text not null,
    app_version text not null,
    service_version text,
    capabilities jsonb not null default '{}'::jsonb,
    unattended_enabled boolean not null default false,
    status text not null check (status in ('ACTIVE','REVOKED','DECOMMISSIONED')),
    authorization_version bigint not null default 1 check (authorization_version >= 1),
    enrolled_at timestamptz not null,
    updated_at timestamptz not null,
    last_seen_at timestamptz,
    revoked_at timestamptz,
    decommissioned_at timestamptz,
    unique (tenant_id, installation_id),
    unique (id, tenant_id)
);
create index ix_devices_tenant_status on devices(tenant_id, status);
create index ix_devices_last_seen on devices(tenant_id, last_seen_at desc);

create table device_keys (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    device_id uuid not null,
    key_version integer not null check (key_version >= 1),
    public_key bytea not null,
    public_key_thumbprint bytea not null,
    status text not null check (status in ('ACTIVE','ROTATING','REVOKED','RETIRED')),
    valid_from timestamptz not null,
    valid_until timestamptz,
    revoked_at timestamptz,
    created_at timestamptz not null,
    unique (device_id, key_version),
    unique (public_key_thumbprint),
    check (octet_length(public_key_thumbprint) = 32),
    foreign key (device_id, tenant_id) references devices(id, tenant_id) on delete cascade
);
create unique index ux_device_one_active_key on device_keys(device_id)
  where status = 'ACTIVE';

create table device_group_members (
    tenant_id uuid not null references tenants(id) on delete cascade,
    device_group_id uuid not null,
    device_id uuid not null,
    added_at timestamptz not null,
    added_by_user_id uuid references users(id),
    primary key (device_group_id, device_id),
    foreign key (device_group_id, tenant_id) references device_groups(id, tenant_id) on delete cascade,
    foreign key (device_id, tenant_id) references devices(id, tenant_id) on delete cascade
);
create index ix_device_group_members_device on device_group_members(tenant_id, device_id);

create table device_enrollment_tokens (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    token_lookup_hash bytea not null unique,
    device_group_id uuid,
    created_by_user_id uuid not null references users(id),
    max_uses integer not null check (max_uses between 1 and 1000),
    use_count integer not null default 0 check (use_count >= 0),
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null,
    check (use_count <= max_uses),
    check (octet_length(token_lookup_hash) = 32),
    foreign key (device_group_id, tenant_id) references device_groups(id, tenant_id)
);
create index ix_enrollment_tokens_expiry on device_enrollment_tokens(expires_at)
  where revoked_at is null;

create table device_credential_challenges (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    device_id uuid not null,
    key_version integer not null check (key_version >= 1),
    purpose text not null check (purpose in ('CREDENTIAL_REFRESH','KEY_ROTATION')),
    nonce_hash bytea not null unique,
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null,
    check (octet_length(nonce_hash) = 32),
    foreign key (device_id, tenant_id) references devices(id, tenant_id) on delete cascade
);
create index ix_device_credential_challenges_expiry on device_credential_challenges(expires_at)
  where consumed_at is null;

create table tenant_invitations (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    email_normalized text not null,
    roles text[] not null,
    token_lookup_hash bytea not null unique,
    status text not null check (status in ('PENDING','ACCEPTED','REVOKED','EXPIRED')),
    invited_by_user_id uuid not null references users(id),
    expires_at timestamptz not null,
    accepted_by_user_id uuid references users(id),
    accepted_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz not null,
    check (roles <@ array['ADMIN','SECURITY_AUDITOR','OPERATOR','READ_ONLY_ANALYST']::text[]),
    check (cardinality(roles) > 0),
    check (octet_length(token_lookup_hash) = 32),
    unique (tenant_id, email_normalized, status)
);

create table data_export_requests (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    requested_by_user_id uuid not null references users(id),
    export_format text not null check (export_format in ('JSONL','CSV_BUNDLE')),
    state text not null check (state in ('QUEUED','RUNNING','READY','FAILED','EXPIRED')),
    object_key text,
    object_sha256 bytea,
    requested_at timestamptz not null,
    completed_at timestamptz,
    download_expires_at timestamptz,
    failure_code text,
    check (object_sha256 is null or octet_length(object_sha256) = 32)
);

create table tenant_closure_requests (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    requested_by_user_id uuid not null references users(id),
    state text not null check (state in ('PENDING_REAUTH','COOLING_OFF','SCHEDULED','CANCELLED','COMPLETED')),
    reason_redacted text not null,
    requested_at timestamptz not null,
    effective_at timestamptz not null,
    reauthenticated_at timestamptz,
    cancelled_at timestamptz,
    completed_at timestamptz
);

create table policies (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    name text not null,
    description text,
    status text not null check (status in ('DRAFT','ACTIVE','DISABLED')),
    active_version integer,
    resource_version bigint not null default 1 check (resource_version >= 1),
    created_by_user_id uuid not null references users(id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (tenant_id, name),
    unique (id, tenant_id),
    check (active_version is null or active_version >= 1)
);

create table policy_versions (
    policy_id uuid not null,
    tenant_id uuid not null references tenants(id) on delete cascade,
    version integer not null check (version >= 1),
    policy_document jsonb not null,
    schema_version integer not null check (schema_version >= 1),
    document_hash bytea not null,
    created_by_user_id uuid not null references users(id),
    created_at timestamptz not null,
    activated_at timestamptz,
    primary key (policy_id, version),
    check (octet_length(document_hash) = 32),
    foreign key (policy_id, tenant_id) references policies(id, tenant_id) on delete cascade
);
create index ix_policy_versions_tenant on policy_versions(tenant_id, created_at desc);

alter table policies
  add constraint fk_policies_active_version
  foreign key (id, active_version) references policy_versions(policy_id, version)
  deferrable initially deferred;

create table policy_decisions (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    session_id uuid,
    operator_user_id uuid not null references users(id),
    device_id uuid,
    input_hash bytea not null,
    decision jsonb not null,
    policy_version_refs jsonb not null,
    authorization_version bigint not null,
    evaluated_at timestamptz not null,
    expires_at timestamptz,
    check (octet_length(input_hash) = 32),
    unique (id, tenant_id),
    foreign key (device_id, tenant_id) references devices(id, tenant_id)
);
create index ix_policy_decisions_tenant_time on policy_decisions(tenant_id, evaluated_at desc);

create table support_sessions (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    session_type text not null check (session_type in ('ATTENDED','MANAGED_ATTENDED','UNATTENDED')),
    host_device_id uuid,
    operator_user_id uuid references users(id),
    policy_decision_id uuid,
    state text not null check (state in (
      'CREATED','WAITING_FOR_OPERATOR','CONSENT_PENDING','HOST_PENDING','AUTHORIZED','NEGOTIATING',
      'CONNECTED','RECONNECTING','EXPIRED','REJECTED','FAILED','CANCELLED','ENDED'
    )),
    state_version bigint not null check (state_version >= 1),
    permission_revision bigint not null default 0 check (permission_revision >= 0),
    transport_epoch bigint not null default 0 check (transport_epoch >= 0),
    requested_scopes text[] not null,
    granted_scopes text[] not null default '{}',
    route_class text check (route_class in ('DIRECT','TURN_UDP','TURN_TCP','TURN_TLS')),
    created_at timestamptz not null,
    authorized_at timestamptz,
    connected_at timestamptz,
    ended_at timestamptz,
    end_reason text,
    expires_at timestamptz not null,
    check (requested_scopes <@ array[
      'VIEW_SCREEN','CONTROL_POINTER','CONTROL_KEYBOARD',
      'SYNC_CLIPBOARD_TEXT_HOST_TO_OPERATOR','SYNC_CLIPBOARD_TEXT_OPERATOR_TO_HOST',
      'TRANSFER_FILE_HOST_TO_OPERATOR','TRANSFER_FILE_OPERATOR_TO_HOST','CHAT',
      'SWITCH_MONITOR','REQUEST_REBOOT','RECONNECT_AFTER_REBOOT','UNATTENDED_SESSION'
    ]::text[]),
    check (granted_scopes <@ requested_scopes),
    check (tenant_id is not null or (session_type = 'ATTENDED' and state in ('CREATED','WAITING_FOR_OPERATOR'))),
    check ((session_type = 'ATTENDED' and host_device_id is null) or session_type <> 'ATTENDED'),
    check ((session_type <> 'UNATTENDED') or ('UNATTENDED_SESSION' = any(granted_scopes))),
    unique (id, tenant_id),
    foreign key (host_device_id, tenant_id) references devices(id, tenant_id),
    foreign key (policy_decision_id, tenant_id) references policy_decisions(id, tenant_id)
);
create index ix_sessions_tenant_created on support_sessions(tenant_id, created_at desc);
create index ix_sessions_operator_created on support_sessions(operator_user_id, created_at desc);
create index ix_sessions_device_created on support_sessions(host_device_id, created_at desc);
create index ix_sessions_active on support_sessions(state, expires_at)
  where state not in ('ENDED','EXPIRED','REJECTED','FAILED','CANCELLED');
create index ix_sessions_expiry on support_sessions(expires_at)
  where state not in ('ENDED','EXPIRED','REJECTED','FAILED','CANCELLED');

alter table policy_decisions
  add constraint fk_policy_decisions_session
  foreign key (session_id) references support_sessions(id)
  deferrable initially deferred;

create table session_participants (
    id uuid primary key,
    session_id uuid not null,
    tenant_id uuid references tenants(id),
    peer_id uuid not null,
    role text not null check (role in ('HOST','OPERATOR')),
    user_id uuid references users(id),
    device_id uuid,
    ephemeral_public_key bytea not null,
    public_key_thumbprint bytea not null,
    token_subject text not null,
    status text not null check (status in ('PENDING','AUTHORIZED','CONNECTED','DISCONNECTED','REVOKED')),
    authorization_version bigint not null check (authorization_version >= 1),
    created_at timestamptz not null,
    authorized_at timestamptz,
    last_seen_at timestamptz,
    revoked_at timestamptz,
    unique (session_id, peer_id),
    unique (session_id, role),
    check (octet_length(public_key_thumbprint) = 32),
    check ((role = 'OPERATOR' and user_id is not null) or role <> 'OPERATOR'),
    foreign key (session_id, tenant_id) references support_sessions(id, tenant_id) on delete cascade,
    foreign key (device_id, tenant_id) references devices(id, tenant_id)
);
create index ix_session_participants_peer on session_participants(peer_id, status);

create table session_bootstrap_credentials (
    id uuid primary key,
    session_id uuid not null references support_sessions(id) on delete cascade,
    participant_id uuid not null references session_participants(id) on delete cascade,
    token_lookup_hash bytea not null unique,
    purpose text not null check (purpose in ('HOST_BOOTSTRAP','OPERATOR_BOOTSTRAP','RECONNECT','REBOOT_RECONNECT')),
    max_uses integer not null check (max_uses between 1 and 10),
    use_count integer not null default 0 check (use_count >= 0),
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null,
    check (use_count <= max_uses),
    check (octet_length(token_lookup_hash) = 32)
);
create index ix_bootstrap_expiry on session_bootstrap_credentials(expires_at)
  where consumed_at is null;

-- code_lookup_hash is HMAC-SHA-256 over the canonical support code using a versioned server lookup key; raw/unkeyed code material is never stored.
create table session_code_lookups (
    session_id uuid primary key references support_sessions(id) on delete cascade,
    code_lookup_hash bytea not null unique,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    locked_until timestamptz,
    expires_at timestamptz not null,
    check (octet_length(code_lookup_hash) = 32)
);

create table proof_nonces (
    id uuid primary key,
    session_id uuid not null references support_sessions(id) on delete cascade,
    participant_id uuid not null references session_participants(id) on delete cascade,
    nonce_hash bytea not null unique,
    purpose text not null check (purpose in ('PEER_AUTHORIZATION','DEVICE_ENROLLMENT','DEVICE_TOKEN_REFRESH','CONSENT_DECISION','MANAGED_HOST_DECISION','DEVICE_KEY_ROTATION')),
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null,
    check (octet_length(nonce_hash) = 32)
);
create index ix_proof_nonces_expiry on proof_nonces(expires_at)
  where consumed_at is null;

create table session_events (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    session_id uuid not null,
    event_sequence bigint not null check (event_sequence >= 1),
    event_type text not null,
    actor_type text not null,
    actor_id text,
    occurred_at timestamptz not null,
    details jsonb not null,
    previous_hash bytea,
    event_hash bytea not null,
    unique (session_id, event_sequence),
    check (previous_hash is null or octet_length(previous_hash) = 32),
    check (octet_length(event_hash) = 32),
    foreign key (session_id, tenant_id) references support_sessions(id, tenant_id) on delete cascade
);
create index ix_session_events_session_time on session_events(session_id, occurred_at);

create table audit_chains (
    chain_scope text primary key,
    last_sequence bigint not null default 0 check (last_sequence >= 0),
    last_hash bytea,
    updated_at timestamptz not null,
    check (last_hash is null or octet_length(last_hash) = 32)
);

create table audit_events (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    chain_scope text not null references audit_chains(chain_scope),
    chain_sequence bigint not null check (chain_sequence >= 1),
    category text not null,
    action text not null,
    outcome text not null,
    actor_type text not null,
    actor_id text,
    target_type text,
    target_id text,
    correlation_id uuid not null,
    occurred_at timestamptz not null,
    source_ip inet,
    details jsonb not null,
    previous_hash bytea,
    event_hash bytea not null,
    unique (chain_scope, chain_sequence),
    unique (id, tenant_id),
    check (previous_hash is null or octet_length(previous_hash) = 32),
    check (octet_length(event_hash) = 32)
);
create index ix_audit_tenant_time on audit_events(tenant_id, occurred_at desc);
create index ix_audit_correlation on audit_events(correlation_id);
create index ix_audit_category_time on audit_events(category, occurred_at desc);

create table update_releases (
    id uuid primary key,
    product text not null,
    channel text not null check (channel in ('internal','canary','stable')),
    version text not null,
    release_sequence bigint not null check (release_sequence >= 1),
    minimum_allowed_sequence bigint not null check (minimum_allowed_sequence >= 0),
    status text not null check (status in ('DRAFT','PUBLISHED','REVOKED','SUPERSEDED')),
    rollout_percent integer not null default 0 check (rollout_percent between 0 and 100),
    metadata_version bigint not null check (metadata_version >= 1),
    published_at timestamptz,
    expires_at timestamptz not null,
    created_at timestamptz not null,
    unique (product, channel, release_sequence),
    check (minimum_allowed_sequence <= release_sequence)
);

create table update_artifacts (
    id uuid primary key,
    release_id uuid not null references update_releases(id) on delete cascade,
    architecture text not null check (architecture in ('x64','arm64')),
    package_type text not null check (package_type in ('PORTABLE_AGENT','OPERATOR_INSTALLER','MANAGED_HOST_INSTALLER')),
    object_key text not null,
    byte_size bigint not null check (byte_size > 0),
    sha256 bytea not null,
    authenticode_signer_thumbprint text not null,
    created_at timestamptz not null,
    unique (release_id, architecture, package_type),
    check (octet_length(sha256) = 32)
);

create table device_update_status (
    tenant_id uuid not null references tenants(id) on delete cascade,
    device_id uuid not null,
    release_id uuid not null references update_releases(id),
    state text not null check (state in ('ELIGIBLE','DOWNLOADING','INSTALLING','SUCCEEDED','FAILED','ROLLED_BACK','DEFERRED')),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    last_error_code text,
    first_seen_at timestamptz not null,
    updated_at timestamptz not null,
    primary key (device_id, release_id),
    foreign key (device_id, tenant_id) references devices(id, tenant_id) on delete cascade
);
create index ix_device_update_release_state on device_update_status(release_id, state);

create table webhook_endpoints (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    endpoint_url text not null,
    secret_reference text not null,
    subscribed_events text[] not null,
    status text not null check (status in ('ACTIVE','DISABLED')),
    created_by_user_id uuid not null references users(id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (id, tenant_id)
);

create table webhook_deliveries (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    webhook_endpoint_id uuid not null,
    audit_event_id uuid,
    event_id uuid not null,
    state text not null check (state in ('PENDING','DELIVERED','FAILED','DEAD_LETTER')),
    attempts integer not null default 0 check (attempts >= 0),
    next_attempt_at timestamptz,
    delivered_at timestamptz,
    last_status_code integer,
    last_error_code text,
    created_at timestamptz not null,
    unique (webhook_endpoint_id, event_id),
    foreign key (webhook_endpoint_id, tenant_id) references webhook_endpoints(id, tenant_id) on delete cascade,
    foreign key (audit_event_id, tenant_id) references audit_events(id, tenant_id)
);
create index ix_webhook_pending on webhook_deliveries(next_attempt_at)
  where state in ('PENDING','FAILED');

create table usage_meter_events (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    session_id uuid,
    meter_type text not null check (meter_type in ('SESSION_SECOND','TURN_INGRESS_BYTE','TURN_EGRESS_BYTE','FILE_TRANSFER_BYTE')),
    quantity bigint not null check (quantity >= 0),
    region text,
    transport text,
    occurred_at timestamptz not null,
    idempotency_key text not null unique,
    foreign key (session_id, tenant_id) references support_sessions(id, tenant_id)
);
create index ix_usage_tenant_time on usage_meter_events(tenant_id, occurred_at);

create table abuse_cases (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    session_id uuid,
    category text not null check (category in ('SCAM','UNAUTHORIZED_ACCESS','HARASSMENT','MALWARE','OTHER')),
    status text not null check (status in ('OPEN','TRIAGED','ACTIONED','CLOSED')),
    reporter_type text not null,
    reporter_id text,
    description_redacted text not null,
    assigned_to text,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    closed_at timestamptz,
    foreign key (session_id, tenant_id) references support_sessions(id, tenant_id)
);
create index ix_abuse_open on abuse_cases(status, created_at)
  where status <> 'CLOSED';

create table legal_holds (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    scope_type text not null,
    scope_id text not null,
    reason_reference text not null,
    status text not null check (status in ('ACTIVE','RELEASED')),
    created_by text not null,
    created_at timestamptz not null,
    released_at timestamptz
);

create table outbox_messages (
    id uuid primary key,
    tenant_id uuid references tenants(id),
    occurred_at timestamptz not null,
    type text not null,
    payload jsonb not null,
    attempts integer not null default 0 check (attempts >= 0),
    next_attempt_at timestamptz not null,
    processed_at timestamptz,
    last_error_code text
);
create index ix_outbox_pending on outbox_messages(next_attempt_at)
  where processed_at is null;

create table idempotency_records (
    scope text not null,
    tenant_id uuid,
    actor_subject text not null,
    idempotency_key text not null,
    request_hash bytea not null,
    response_status integer not null,
    response_headers jsonb not null default '{}'::jsonb,
    response_body jsonb,
    created_at timestamptz not null,
    expires_at timestamptz not null,
    primary key (scope, actor_subject, idempotency_key),
    check (octet_length(request_hash) = 32)
);
create index ix_idempotency_expiry on idempotency_records(expires_at);

-- Defense-in-depth tenant isolation. Application transactions set:
--   set local app.tenant_id = '<tenant uuid>';
-- Migration/maintenance roles are separate and explicitly audited.

alter table tenant_settings enable row level security;
alter table memberships enable row level security;
alter table device_groups enable row level security;
alter table devices enable row level security;
alter table device_keys enable row level security;
alter table device_group_members enable row level security;
alter table device_enrollment_tokens enable row level security;
alter table device_credential_challenges enable row level security;
alter table tenant_invitations enable row level security;
alter table data_export_requests enable row level security;
alter table tenant_closure_requests enable row level security;
alter table policies enable row level security;
alter table policy_versions enable row level security;
alter table policy_decisions enable row level security;
alter table support_sessions enable row level security;
alter table session_participants enable row level security;
alter table session_events enable row level security;
alter table audit_events enable row level security;
alter table device_update_status enable row level security;
alter table webhook_endpoints enable row level security;
alter table webhook_deliveries enable row level security;
alter table usage_meter_events enable row level security;
alter table abuse_cases enable row level security;
alter table legal_holds enable row level security;

create policy tenant_settings_isolation on tenant_settings
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy memberships_isolation on memberships
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy device_groups_isolation on device_groups
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy devices_isolation on devices
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy device_keys_isolation on device_keys
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy device_group_members_isolation on device_group_members
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy enrollment_tokens_isolation on device_enrollment_tokens
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy policies_isolation on policies
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy policy_versions_isolation on policy_versions
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy policy_decisions_isolation on policy_decisions
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy device_credential_challenges_isolation on device_credential_challenges
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy tenant_invitations_isolation on tenant_invitations
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy data_export_requests_isolation on data_export_requests
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy tenant_closure_requests_isolation on tenant_closure_requests
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);

create policy support_sessions_isolation on support_sessions
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy session_participants_isolation on session_participants
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy session_events_isolation on session_events
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy audit_events_isolation on audit_events
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy device_update_status_isolation on device_update_status
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy webhook_endpoints_isolation on webhook_endpoints
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy webhook_deliveries_isolation on webhook_deliveries
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy usage_meter_events_isolation on usage_meter_events
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy abuse_cases_isolation on abuse_cases
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
create policy legal_holds_isolation on legal_holds
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id is null or tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
