name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Build, test, and inspect dependencies
        shell: pwsh
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: '1'
          DOTNET_NOLOGO: '1'
        run: ./build.ps1 -Target CI -Configuration Release

